### ISSUE TITLE
Sparql Reader queryPeople() returns unused organization

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss-labs/rialto-derivatives#110]
Organization isn't used and may produce multiple results for a single user since a user may belong to more than one organization.

refs #104

**Comment by jcoyne** [comment]
I don't understand this. Can you provide more context?

**Comment by justinlittman** [comment]
Ooops. I already cleaned it up in https://github.com/sul-dlss-labs/rialto-derivatives/commit/6892ff89ac3bbe5030185eb215fd8695c2e2ac9a#diff-ca828bcde0402e901520145ae69f01b4
